import * as THREE from 'three'
import type { Building } from '../../../types/city'
import {
  createSkyscraperGeometry,
  createApartmentTowerGeometry,
  createMidRiseApartmentGeometry,
  createSuburbanHouseGeometry,
  createWarehouseGeometry,
  createFactoryGeometry,
  createHospitalGeometry,
  createSchoolGeometry,
  createConstructionSiteGeometry,
  createCommercialRetailGeometry,
  createGovernmentGeometry,
  createTransitHubGeometry,
  createParkPavilionGeometry,
  type BuildingArchetypeGeometries,
} from './BuildingArchetypes'
import { getBuildingMaterials } from './BuildingMaterials'

export type ArchetypeCategory =
  | 'skyscraper'
  | 'apartment_high'
  | 'apartment_mid'
  | 'suburban_house'
  | 'warehouse'
  | 'factory'
  | 'hospital'
  | 'school'
  | 'construction'
  | 'commercial_retail'
  | 'government'
  | 'transit_hub'
  | 'park_pavilion'

// Deterministic string hash
function hashString(str: string): number {
  let hash = 0
  for (let i = 0; i < str.length; i++) {
    hash = (hash << 5) - hash + str.charCodeAt(i)
    hash |= 0
  }
  return Math.abs(hash)
}

/**
 * Maps a simulation building to its visual archetype based on building_type, height, and district.
 * Covers all 12 district types generated by the backend city generator.
 */
export function determineBuildingArchetype(b: Building): ArchetypeCategory {
  const bType = (b.building_type || b.type || '').toLowerCase()
  const h = b.height || 10
  const hash = hashString(b.id || `${b.x}_${b.z}`)

  // Explicit civic/service types
  if (bType.includes('developing') || bType.includes('construction')) {
    return 'construction'
  }
  if (bType.includes('hospital') || bType.includes('medical') || bType.includes('healthcare')) {
    return 'hospital'
  }
  if (bType.includes('education') || bType.includes('university') || bType.includes('school')) {
    return 'school'
  }
  if (bType.includes('police') || bType.includes('fire') || bType.includes('government') || bType.includes('city_hall')) {
    return 'government'
  }
  if (bType.includes('park') || bType.includes('recreation') || bType.includes('pavilion')) {
    return 'park_pavilion'
  }
  if (bType.includes('transport') || bType.includes('metro') || bType.includes('railway') || bType.includes('transit') || bType.includes('bus_stop')) {
    return 'transit_hub'
  }
  if (bType.includes('industrial') || bType.includes('factory')) {
    return h > 18 ? 'factory' : 'warehouse'
  }
  if (bType.includes('logistics') || bType.includes('warehouse')) {
    return 'warehouse'
  }
  if (bType.includes('commercial') || bType.includes('retail') || bType.includes('shop') || bType.includes('restaurant')) {
    return 'commercial_retail'
  }

  // District-type based mapping
  if (bType.includes('cbd')) {
    return h > 40 ? 'skyscraper' : h > 20 ? 'apartment_high' : 'commercial_retail'
  }
  if (bType.includes('tech') || bType.includes('office')) {
    return h > 35 ? 'skyscraper' : 'apartment_high'
  }
  if (bType.includes('riverfront')) {
    return h > 30 ? 'apartment_high' : (hash % 3 === 0 ? 'commercial_retail' : 'apartment_mid')
  }
  if (bType.includes('residential_high')) {
    return 'apartment_high'
  }
  if (bType.includes('residential_med')) {
    return 'apartment_mid'
  }
  if (bType.includes('suburban') || bType.includes('residential_low') || bType.includes('rural')) {
    return h > 12 ? 'apartment_mid' : 'suburban_house'
  }

  // Height-based fallback
  if (h > 50) return 'skyscraper'
  if (h > 28) return 'apartment_high'
  if (h > 14) return 'apartment_mid'
  if (h > 8) return hash % 3 === 0 ? 'commercial_retail' : 'suburban_house'
  return 'suburban_house'
}

/**
 * Geometry Cache to avoid redundant allocations while maintaining rich variety
 */
const geometryCache: Map<string, BuildingArchetypeGeometries> = new Map()

export function getBuildingGeometry(b: Building, archetype: ArchetypeCategory): BuildingArchetypeGeometries {
  // Quantize dimensions to bucket geometries for high reuse & GPU efficiency
  const w = Math.round(b.width || 20)
  const d = Math.round(b.depth || 20)
  const h = Math.round(b.height || 15)
  const cacheKey = `${archetype}_${w}_${d}_${h}`

  if (geometryCache.has(cacheKey)) {
    return geometryCache.get(cacheKey)!
  }

  let geom: BuildingArchetypeGeometries

  switch (archetype) {
    case 'skyscraper':
      geom = createSkyscraperGeometry(w, d, h)
      break
    case 'apartment_high':
      geom = createApartmentTowerGeometry(w, d, h)
      break
    case 'apartment_mid':
      geom = createMidRiseApartmentGeometry(w, d, h)
      break
    case 'suburban_house':
      geom = createSuburbanHouseGeometry(w, d, h)
      break
    case 'warehouse':
      geom = createWarehouseGeometry(w, d, h)
      break
    case 'factory':
      geom = createFactoryGeometry(w, d, h)
      break
    case 'hospital':
      geom = createHospitalGeometry(w, d, h)
      break
    case 'school':
      geom = createSchoolGeometry(w, d, h)
      break
    case 'construction':
      geom = createConstructionSiteGeometry(w, d, h)
      break
    case 'commercial_retail':
      geom = createCommercialRetailGeometry(w, d, h)
      break
    case 'government':
      geom = createGovernmentGeometry(w, d, h)
      break
    case 'transit_hub':
      geom = createTransitHubGeometry(w, d, h)
      break
    case 'park_pavilion':
      geom = createParkPavilionGeometry(w, d, h)
      break
    default:
      geom = createSuburbanHouseGeometry(w, d, h)
  }

  geometryCache.set(cacheKey, geom)
  return geom
}

/**
 * Returns appropriate PBR material for the archetype and time-of-day.
 * Each archetype gets a visually distinct material palette.
 */
export function getMaterialForArchetype(
  archetype: ArchetypeCategory,
  isNight: boolean
): { body: THREE.Material; details: THREE.Material; accent?: THREE.Material } {
  const mats = getBuildingMaterials(isNight)

  switch (archetype) {
    case 'skyscraper':
      return { body: mats.glassOffice, details: mats.darkTrim, accent: mats.scaffoldYellow }
    case 'apartment_high':
      return { body: mats.residentialHigh, details: mats.concrete }
    case 'apartment_mid':
      return { body: mats.brick, details: mats.concrete }
    case 'suburban_house':
      return { body: mats.concrete, details: mats.roofTile }
    case 'warehouse':
      return { body: mats.industrialMetal, details: mats.darkTrim }
    case 'factory':
      return { body: mats.industrialMetal, details: mats.concrete }
    case 'hospital':
      return { body: mats.concrete, details: mats.glassOffice }
    case 'school':
      return { body: mats.brick, details: mats.roofGravel }
    case 'construction':
      return { body: mats.concrete, details: mats.scaffoldYellow, accent: mats.scaffoldYellow }
    case 'commercial_retail':
      return { body: mats.brick, details: mats.glassOffice, accent: mats.darkTrim }
    case 'government':
      return { body: mats.concrete, details: mats.darkTrim }
    case 'transit_hub':
      return { body: mats.darkTrim, details: mats.glassOffice }
    case 'park_pavilion':
      return { body: mats.concrete, details: mats.roofTile }
  }
}
